spring:
  datasource:
    url: jdbc:mysql://${MySQL_DB_URL}:${MySQL_DB_PORT}/anima_web?useSSL=false&serverTimezone=UTC
    username: ${MySQL_DB_USERNAME}
    password: ${MySQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3

proxy:
  enabled: true  # 设置为 true 启用代理
  host: 127.0.0.1
  port: 10808

logging:
  level:
    com.zorth.anima: DEBUG
    org.springframework.web: INFO 

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    base-url: https://openrouter.ai/api/v1
    default-model: google/gemini-2.5-flash-preview